name: CI
on:
  push:
    branches:
      -  main
jobs:
  Build:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v4
      - name: Build
        run: |
          docker build .
      
      
  
